name: Qodo Merge PR Review

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Qodo Merge
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.ANTHROPIC_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          config.model: "claude-3-5-sonnet"  # 使用するモデルを指定
          pr_reviewer.extra_instructions: "回答は必ず全て日本語で記述してください。"  
